=== pdhoot16/Adventure-Works/XML/ResellerSales_Fact_table.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<xsd:element name="ResellerSales_Fact_table">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="dimGeography" minOccurs="1" maxOccurs="unbounded" />
<xsd:element ref="dimReseller" minOccurs="1" maxOccurs="unbounded" />
<xsd:element ref="dimPromotion" minOccurs="1" maxOccurs="unbounded" />
<xsd:element ref="dimProduct" minOccurs="1" maxOccurs="unbounded" />
<xsd:element ref="dimDate" minOccurs="1" maxOccurs="unbounded" />
<xsd:element ref="factResellerSales" minOccurs="1" maxOccurs="unbounded" />
</xsd:sequence>
</xsd:complexType>
<xsd:key name="dimGeography_key">
<xsd:selector xpath="dimGeography/geographykey" />
<xsd:field xpath="." />
</xsd:key>
<xsd:keyref name="dimGeography_key_ref" refer="dimGeography_key">
<xsd:selector xpath="dimReseller/geographykey" />
<xsd:field xpath="." />
</xsd:keyref>
<xsd:key name="dimReseller_key">
<xsd:selector xpath="dimReseller/resellerKey" />
<xsd:field xpath="." />
</xsd:key>
<xsd:keyref name="dimReseller_key_ref" refer="dimReseller_key">
<xsd:selector xpath="factResellerSales/resellerkey" />
<xsd:field xpath="." />
</xsd:keyref>
<xsd:key name="dimPromotion_key">
<xsd:selector xpath="dimPromotion/promotionkey" />
<xsd:field xpath="." />
</xsd:key>
<xsd:keyref name="dimPromotion_key_ref" refer="dimPromotion_key">
<xsd:selector xpath="factResellerSales/promotionkey" />
<xsd:field xpath="." />
</xsd:keyref>
<xsd:key name="dimProduct_key">
<xsd:selector xpath="dimProduct/productkey" />
<xsd:field xpath="." />
</xsd:key>
<xsd:keyref name="dimProduct_key_ref" refer="dimProduct_key">
<xsd:selector xpath="factResellerSales/productkey" />
<xsd:field xpath="." />
</xsd:keyref>
<xsd:key name="dimDate_key">
<xsd:selector xpath="dimDate/datekey" />
<xsd:field xpath="." />
</xsd:key>
<xsd:keyref name="dimDate_key_ref" refer="dimDate_key">
<xsd:selector xpath="factResellerSales/datekey" />
<xsd:field xpath="." />
</xsd:keyref>
</xsd:element>
<xsd:element name="dimGeography">
<xsd:complexType>
<xsd:sequence>
<xsd:element name="geographykey" type="xsd:string" />
<xsd:element name="City" type="xsd:string" />
<xsd:element name="StateProvinceCode" type="xsd:string" />
<xsd:element name="StateProvinceName" type="xsd:string" />
<xsd:element name="CountryRegionCode" type="xsd:string" />
<xsd:element name="EnglishCountryRegionName" type="xsd:string" />
<xsd:element name="SpanishCountryRegionName" type="xsd:string" />
<xsd:element name="FrenchCountryRegionName" type="xsd:string" />
<xsd:element name="PostalCode" type="xsd:string" />
<xsd:element name="SalesTerritoryKey" type="xsd:string" />
<xsd:element name="IpAddressLocator" type="xsd:string" />
</xsd:sequence>
</xsd:complexType>
</xsd:element>
<xsd:element name="dimReseller">
<xsd:complexType>
<xsd:sequence>
<xsd:element name="resellerkey" type="xsd:string" />
<xsd:element name="geographykey" type="xsd:string" />
<xsd:element name="ResellerAlternateKey" type="xsd:string" />
<xsd:element name="Phone" type="xsd:string" />
<xsd:element name="BusinessType" type="xsd:string" />
<xsd:element name="ResellerName" type="xsd:string" />
<xsd:element name="NumberEmployees" type="xsd:string" />
<xsd:element name="OrderFrequency" type="xsd:string" />
<xsd:element name="OrderMonth" type="xsd:string" />
<xsd:element name="FirstOrderYear" type="xsd:string" />
<xsd:element name="LastOrderYear" type="xsd:string" />
<xsd:element name="ProductLine" type="xsd:string" />
<xsd:element name="AddressLine1" type="xsd:string" />
<xsd:element name="AddressLine2" type="xsd:string" />
<xsd:element name="AnnualSales" type="xsd:string" />
<xsd:element name="BankName" type="xsd:string" />
<xsd:element name="MinPaymentType" type="xsd:string" />
<xsd:element name="MinPaymentAmount" type="xsd:string" />
<xsd:element name="AnnualRevenue" type="xsd:string" />
<xsd:element name="YearOpened" type="xsd:string" />
</xsd:sequence>
</xsd:complexType>
</xsd:element>
<xsd:element name="dimPromotion">
<xsd:complexType>
<xsd:sequence>
<xsd:element name="promotionkey" type="xsd:string" />
<xsd:element name="PromotionAlternateKey" type="xsd:string" />
<xsd:element name="EnglishPromotionName" type="xsd:string" />
<xsd:element name="SpanishPromotionName" type="xsd:string" />
<xsd:element name="FrenchPromotionName" type="xsd:string" />
<xsd:element name="DiscountPct" type="xsd:string" />
<xsd:element name="EnglishPromotionType" type="xsd:string" />
<xsd:element name="SpanishPromotionType" type="xsd:string" />
<xsd:element name="FrenchPromotionType" type="xsd:string" />
<xsd:element name="EnglishPromotionCategory" type="xsd:string" />
<xsd:element name="SpanishPromotionCategory" type="xsd:string" />
<xsd:element name="FrenchPromotionCategory" type="xsd:string" />
<xsd:element name="StartDate" type="xsd:string" />
<xsd:element name="EndDate" type="xsd:string" />
<xsd:element name="MinQty" type="xsd:string" />
<xsd:element name="MaxQty" type="xsd:string" />
</xsd:sequence>
</xsd:complexType>
</xsd:element>

<xsd:element name="dimProduct">
<xsd:complexType>
<xsd:sequence>
<xsd:element name="productkey" type="xsd:string" />
<xsd:element name="ProductAlternateKey" type="xsd:string" />
<xsd:element name="ProductSubcategoryKey" type="xsd:string" />
<xsd:element name="WeightUnitMeasureCode" type="xsd:string" />
<xsd:element name="SizeUnitMeasureCode" type="xsd:string" />
<xsd:element name="EnglishProductName" type="xsd:string" />
<xsd:element name="SpanishProductName" type="xsd:string" />
<xsd:element name="FrenchProductName" type="xsd:string" />
<xsd:element name="StandardCost" type="xsd:string" />
<xsd:element name="FinishedGoodsFlag" type="xsd:string" />
<xsd:element name="Color" type="xsd:string" />
<xsd:element name="SafetyStockLevel" type="xsd:string" />
<xsd:element name="ReorderPoint" type="xsd:string" />
<xsd:element name="ListPrice" type="xsd:string" />
<xsd:element name="Size" type="xsd:string" />
<xsd:element name="SizeRange" type="xsd:string" />
<xsd:element name="Weight" type="xsd:string" />
<xsd:element name="DaysToManufacture" type="xsd:string" />
<xsd:element name="ProductLine" type="xsd:string" />
<xsd:element name="DealerPrice" type="xsd:string" />
<xsd:element name="Class" type="xsd:string" />
<xsd:element name="Style" type="xsd:string" />
<xsd:element name="ModelName" type="xsd:string" />
<xsd:element name="LargePhoto" type="xsd:string" />
<xsd:element name="EnglishDescription" type="xsd:string" />
<xsd:element name="FrenchDescription" type="xsd:string" />
<xsd:element name="ChineseDescription" type="xsd:string" />
<xsd:element name="ArabicDescription" type="xsd:string" />
<xsd:element name="HebrewDescription" type="xsd:string" />
<xsd:element name="ThaiDescription" type="xsd:string" />
<xsd:element name="GermanDescription" type="xsd:string" />
<xsd:element name="JapaneseDescription" type="xsd:string" />
<xsd:element name="TurkishDescription" type="xsd:string" />
<xsd:element name="StartDate" type="xsd:string" />
<xsd:element name="EndDate" type="xsd:string" />
<xsd:element name="Status" type="xsd:string" />
</xsd:sequence>
</xsd:complexType>
</xsd:element>

<xsd:element name="dimDate">
<xsd:complexType>
<xsd:sequence>
<xsd:element name="datekey" type="xsd:string" />
<xsd:element name="FullDateAlternateKey" type="xsd:string" />
<xsd:element name="DayNumberOfWeek" type="xsd:string" />
<xsd:element name="EnglishDayNameOfWeek" type="xsd:string" />
<xsd:element name="SpanishDayNameOfWeek" type="xsd:string" />
<xsd:element name="FrenchDayNameOfWeek" type="xsd:string" />
<xsd:element name="DayNumberOfMonth" type="xsd:string" />
<xsd:element name="DayNumberOfYear" type="xsd:string" />
<xsd:element name="WeekNumberOfYear" type="xsd:string" />
<xsd:element name="EnglishMonthName" type="xsd:string" />
<xsd:element name="SpanishMonthName" type="xsd:string" />
<xsd:element name="FrenchMonthName" type="xsd:string" />
<xsd:element name="MonthNumberOfYear" type="xsd:string" />
<xsd:element name="CalendarQuarter" type="xsd:string" />
<xsd:element name="CalendarYear" type="xsd:string" />
<xsd:element name="CalendarSemester" type="xsd:string" />
<xsd:element name="FiscalQuarter" type="xsd:string" />
<xsd:element name="FiscalYear" type="xsd:string" />
<xsd:element name="FiscalSemester" type="xsd:string" />
</xsd:sequence>
</xsd:complexType>
</xsd:element>

<xsd:element name="factResellerSales">
<xsd:complexType>
<xsd:all>
<xsd:element name="productkey" type="xsd:string" />
<xsd:element name="datekey" type="xsd:string" />
<xsd:element name="duedate" type="xsd:string" />
<xsd:element name="shipdate" type="xsd:string" />
<xsd:element name="resellerKey" type="xsd:string" />
<xsd:element name="employee" type="xsd:string" />
<xsd:element name="promotionkey" type="xsd:string" />
<xsd:element name="currency" type="xsd:string" />
<xsd:element name="SalesOrderNumber" type="xsd:string" />
<xsd:element name="SalesOrderLineNumber" type="xsd:string" />
<xsd:element name="RevisionNumber" type="xsd:decimal" />
<xsd:element name="OrderQuantity" type="xsd:string" />
<xsd:element name="UnitPrice" type="xsd:decimal" />
<xsd:element name="ExtendedAmount" type="xsd:string" />
<xsd:element name="UnitPriceDiscountPct" type="xsd:string" />
<xsd:element name="DiscountAmount" type="xsd:decimal" />
<xsd:element name="ProductStandardCost" type="xsd:decimal" />
<xsd:element name="TotalProductCost" type="xsd:string" />
<xsd:element name="SalesAmount" type="xsd:string" />
<xsd:element name="TaxAmt" type="xsd:string" />
<xsd:element name="Freight" type="xsd:string" />
<xsd:element name="CarrierTrackingNumber" type="xsd:string" />
<xsd:element name="CustomerPONumber" type="xsd:string" />
<xsd:element name="OrderDate" type="xsd:string" />
<xsd:element name="DueDate" type="xsd:string" />
<xsd:element name="ShipDate" type="xsd:string" />
</xsd:all>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== pdhoot16/Adventure-Works/XML/ResellerSales_Fact_table.xml
<?xml version="1.0"?>
<ResellerSales_Fact_table xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="ResellerSales_Fact_table.xsd">
<dimGeography>
<geographykey>418</geographykey>
<City>Austell</City>
<StateProvinceCode>GA</StateProvinceCode>
<StateProvinceName>Georgia</StateProvinceName>
<CountryRegionCode>US</CountryRegionCode>
<EnglishCountryRegionName>United States</EnglishCountryRegionName>
<SpanishCountryRegionName>Estados Unidos</SpanishCountryRegionName>
<FrenchCountryRegionName>États-Unis</FrenchCountryRegionName>
<PostalCode>30106</PostalCode>
<SalesTerritoryKey>5</SalesTerritoryKey>
<IpAddressLocator>192.0.2.165</IpAddressLocator>
</dimGeography>
<dimReseller>
<resellerkey>676</resellerkey>
<geographykey>418</geographykey>
<ResellerAlternateKey>AW00000676</ResellerAlternateKey>
<Phone>967-555-0129</Phone>
<BusinessType>Value Added Reseller</BusinessType>
<ResellerName>Better Bike Shop</ResellerName>
<NumberEmployees>19</NumberEmployees>
<OrderFrequency>S</OrderFrequency>
<OrderMonth>4</OrderMonth>
<FirstOrderYear>2010</FirstOrderYear>
<LastOrderYear>2013</LastOrderYear>
<ProductLine>Mountain</ProductLine>
<AddressLine1>42525 Austell Road</AddressLine1>
<AddressLine2>NULL</AddressLine2>
<AnnualSales>800000</AnnualSales>
<BankName>United Security</BankName>
<MinPaymentType>NULL</MinPaymentType>
<MinPaymentAmount>NULL</MinPaymentAmount>
<AnnualRevenue>80000</AnnualRevenue>
<YearOpened>1979</YearOpened>
</dimReseller>
<dimPromotion>
<promotionkey>1</promotionkey>
<PromotionAlternateKey>1</PromotionAlternateKey>
<EnglishPromotionName>No Discount</EnglishPromotionName>
<SpanishPromotionName>Sin descuento</SpanishPromotionName>
<FrenchPromotionName>Aucune remise</FrenchPromotionName>
<DiscountPct>0</DiscountPct>
<EnglishPromotionType>No Discount</EnglishPromotionType>
<SpanishPromotionType>Sin descuento</SpanishPromotionType>
<FrenchPromotionType>Aucune remise</FrenchPromotionType>
<EnglishPromotionCategory>No Discount</EnglishPromotionCategory>
<SpanishPromotionCategory>Sin descuento</SpanishPromotionCategory>
<FrenchPromotionCategory>Aucune remise</FrenchPromotionCategory>
<StartDate>12:00:00 AM</StartDate>
<EndDate>12:00:00 AM</EndDate>
<MinQty>0</MinQty>
<MaxQty>NULL</MaxQty>
</dimPromotion>
<dimProduct>
<productkey>349</productkey>
<ProductAlternateKey>BK-M82B-42</ProductAlternateKey>
<ProductSubcategoryKey>1</ProductSubcategoryKey>
<WeightUnitMeasureCode>LB </WeightUnitMeasureCode>
<SizeUnitMeasureCode>CM</SizeUnitMeasureCode>
<EnglishProductName>Mountain-100 Black, 42</EnglishProductName>
<SpanishProductName>Montaña: 100, negra, 42</SpanishProductName>
<FrenchProductName>VTT 100 noir, 42</FrenchProductName>
<StandardCost>1898.0944</StandardCost>
<FinishedGoodsFlag>1</FinishedGoodsFlag>
<Color>Black</Color>
<SafetyStockLevel>100</SafetyStockLevel>
<ReorderPoint>75</ReorderPoint>
<ListPrice>3374.99</ListPrice>
<Size>42</Size>
<SizeRange>42-46 CM</SizeRange>
<Weight>20.77</Weight>
<DaysToManufacture>4</DaysToManufacture>
<ProductLine>M</ProductLine>
<DealerPrice>2024.994</DealerPrice>
<Class>H</Class>
<Style>U</Style>
<ModelName>Mountain-100</ModelName>
<LargePhoto>0x474946383961F0009500F7000074899FC7C8D99499A9040608B6BAC9DCDBF3E1DEE8737987BBC4D4515867DCDBDCFAFAFAECEBFB2B3948282628D3D3D4CBCBE5C2BEC4ECECF3D3D3ECE3E2F4A895954A444B433C42514B52CDCBCDC3C2C3AAACB7FAFDFDE3E3EDFDFDFA99A3B2DAE2E9F1EEF3E3DCDC324356DCDBED4949538A8B963A343AE4E3FA635B634B494DC4BCBBDDDBE3726C72F6F5F658616EF6FAFB3331346969725C5A5CB4B2B4FAFAFED2CED2434144F2F1F2B3ABABA29DA2344D6A535253BCBABD546E8C636163D2CBCB9D9A9ED3D2E562555CB2ADB3F9F7FA3C393DADAAADEEEDEEFDFBFD949195EDF1F5FDFBF6DAD6DBF2ECEDEAE7EAD3D2DB7C7A7E827D83928A8DE6E6E68C8B8D75676A82767CEAE5E5928D92332D326C696CEAE9EAA3A2A4CDC5BCE4E1DD5B545B8382857A757AF6F5FACBD1D9E1E0E1152534D5D5F17371736A636BA8B6C8F6F6FE8DA7C8282B31F1F0FAFDFBFAF8F7F78B858B9B949ABAB5BB50474EB4B4BBC9D7E755525A2A313983848CF1F1FEBAB4B4B0A39BCCC5CB40383EA4A3ACABA5ABAAA4A5FAFDFBF6F3F663636B454348343437C8C5C6B9B1AB0F1820EEEAEEE6E2E6F3F3F4ADB1BCC5C3CB75717995949AD9D4D64A5059DCD9D7F5F3F2EBEAEC2F2A2D989494373236484047797175D9D7F3F6F1EDBABDD0898586E2EAF4F6F9F686827FD6D1CDDEDEF7CCC9C669707DD8D6ECE5EAEEA3BCD7EDEAEAD0CFE5E6E2E2E2E2E5E8E7FB6A6365D4D8E28A909D595055CECDF1EAEDEE9E8F8BF6F5F2E8E7F5F3F6F5E7E6E23C5B7CB4BABEBDB9B5605F5FA4A9BFB5B1C755575BF4F3F9AFB0AFF5F3FE87888CC6C8CC63676EA9A9A7776F6EF1F6F9EDEDEA36383CD8DADD595857261F2544474D767779D8D7E5EBEDEB54769FB7B8B6A5A9AD504F4FEEEBE3191919B2BFE2E2E6E83F3F3F8F8984627DA1C7C8C79D9998F2F5F3E6E9E8494747383736D6D7D71D42692F2F2F202021FDFDFDFFFFFDFFFDFFFDFFFFFFFDFDFDFDFFFDFFFDE3E5E3EFF0F0E9E9FDD9D8FB466283A1B1D48F908ED8D9F1565655D2DFEB6C6D6AA6A8A5989798999D9AF1F8FD464647FEFEFEFFFFFF21F90400000000002C00000000F00095000008FF00FF091C48B0A0C18308132A5CC8B0A1C38710234A9C48B1A2C58B18336ADCC8B1A3C78F20438A1C49B2A4C9932853AA5CC972A5BF963063CA84E9EFE5C09A3373EADCE931C9B981E76CF21C4AB428437F49FE2D488AD3284A7504853A9D8AB066121A541809944A15A43F0E1CD4BD0CCAB52BD5970FA4846971244959B31DD5411DB8E02D5CA349943C4A91C75599BB1FFD2D41C288D11740687A00BE7B68D8A33452B6445ABC1158073BD84880EB566AC4004F94BBC2A96222D6B03451CEA50B2D30098E32407AEC3A648315974AEFE02CD80DE7DD2C091430631B8EED830F726D1C64605DD4DFCF1EF878DC3191C993DBAD94A9784A534CC6B3299EA284FFF154455F90F33A0408E8356F1E9BF700B8E52287C74110E64491FE432286993623339C904608FFBCD4D45D2E64D142022334304209186020C91DB18031C30F3294E203371C4A238D0F3EEC40CE08DA04835F7E491D8186115A58A2450A87B842031C853162D75449B012440B2F3873C30FDC90431F1E466472C70BB9E4B283923B8CB0C30E179878E2503FB182CF0D0E18110326524CE14038A16822060D3776E50F1CB7D592440F07C0E28319D7348349262A38334283CE38534E18E84C39943FEA7813050FCD58E2470A3AD071820AE1C4128B120BF8F9CF6A40F0418B262960D28C392E9E60E80D5ACC108DA4433D70C43F8E38D0CC05B18462C116816CFF31C31652D8185450F89D790826436050A825CD38FAC3090E88F10EA9A516166126985C80C109607411810E626850E0396EE1CA1A52655CD0C205D76C11461C4FCCF16D20D821CB933BE76542AC1F176082812E1110B1C75FFFFC74136BE93C0108182D6242082B0251E2426BE7E8ABAE4E0B7491C209746090891F2704C14206751C110115FF50914137C7868694024000428F0D5298D8D4810BEFB4400F9AFC60811F996040B1141A9011C111472036431497D8E053C270A1D3CE187B5891862EDF0894B0C22D17954114686C41712C5968D26C158E104344105B5850C80C62F45013D4537920C8227C1C32450694D484549951CFA480274AD04A4A12E9ECFF318316BC6481819816C470C216345C0B97071C90820829DE28208807092755F7542E68A0C04FEA70F08F0B5D646289117E14C222065628E69C59E89C03032287E490C32CE7AC73F9624171A02F2B52F8E1BB11279CE00AC162B18ECE138F5FE2C52DFFD87EFB899A68E1AE1F569CCA94F1E31073881C0AB8D5E7F3AC9D83CC165A9C30E7154F1408183AF96810CC3048F8E3C1F7E02FB6C42B90A8D0422C7EE8F0C656DAEA8A2274D08D28E86001E8F000DDEA379431B000017F9044021E11B13EFC8372E740873FD0C1410DFE2952FFB0813734F083E5A48B8167C946001010002924E0490D68C31EFE61B40C7A408167E3C9D96A428339E8630BA35A200AFF75028A15068000F86843355E20890600800CCC13C80DA788B69938E71C2ED0010D3451057D097188329100190210803FF0C0120D9044315C110E6D24200F1A00C74012584599ACAE0C62E0C1050EA13E30E684650439C72B56888030186100F549041E24F1831954E3062538C00758E1B97D0D642E3454895CFE71083A6881195400A41F59223784B80001A8ACC316AE318006986300B01C401B6EC08B1FF0201CCE288600C8500481F4492E1CD8E0FC5462347FC821130E904200474913852C819002A8062CCDD186585AF31ADA9004219851A704984017B31888DA5AC70E62A2E31D2DF08325CCF64566B68415A84480140C014B3C94C3016D304722AC09FF4B45AAA096D57086244AD1885710049327A9C9216271821BFCA52EEE34CA2B50D90857B0720066606439CCE1808E5E949FE670C62F1AD98F12106297C858C9029E70043A34430C45985B4489F20E68AA2096D7C8C33FBE100C346089A30ED0273F07708D72FC6206BC08282FE0788AA8ACC30372114B3B13A28E7628A50C93784004AE702AA2CD74282C2000013A118572C0D201CA90070806C2840CE863061BA5A6033E6ACD36148217BCE0A6240E400D10C04020EAF0C002DE908EA922441D1A5C0019D4408C498C2303DDABE35761A258B136E2070350242F4A3002797C2281561548256810851B98E3B441DD27480D315266F0A00432D8A55604B20EC3FF2E840DF2F001007AA081495C67B23A9100023A81004884630037E0812B7EE18A12F8E0B349E040122CF70F3864801E33B0046AE73AD401C4E0AEBCE0010FBCA90B09C425019278013972B10A1CC814B83301C170091005070C8017B2B2873D7EE00C692CE186E76887206A2095274CC3A7E6B80647133C546CF2E007F6E0C12F0ED0886568E4153C90841906708002E907BE3239071986BB015EC852562388410CB4C15F6920031D1C989C5DE0F0007DFCA21C0AE6285D61790D2522B51ABF90C13E8891D28A6C8007CE80253540BC936712D704FD18403598E10C43E0010F31F8D108B8C10F3A56852054E8011AB4710D057B74A8E6D0C61D66C00C35C231FF1B133900331A405438333927D9E8442708F00C072482172A8EC13E0DF1DD1F6C19061E4C48290792812048A20D89B84647197C4D253263066B8E0235CA500387CC6206BFD8B024FA78E7988C1801D498C10094716371D039B384EE87A101D03CDBFE63161B78061EF4C929EEF213AD4705351A204186252CA40E19DEA700485D6A95BCC40501E84400F2708301D84319E5D08636549B0842FF73046C909F3F563311C59A40120996B476777C0D23FCF3A884A0872EE2779061D8E3D5C468B64CB2814A35A0E1B4BF688332C8DC805CF493D0D5E005B89BF786B054441DA7F8C00BE6CA514BF8BAAE85B8F485A2B081650805073398C1860DC101FAE97B2550FF20EE07EC815C1594C308FA24033276707043F060062398C705BD7A911EA880D7662EC7AE55CB636DA800D4BC90810E88B1806E48789F61F847684FAE123844BB90D59E8132B03D805E08E413AFBE86210C610F668C00153BD7C83BA470653C9821119176400CF00069A2C7A014072805216EFE029CC332DF95A47A450015D5C27F8F651CE477271A2103493363EC1CF6F03FEC80071E8FDDB53BC0060DC3C2418C04A3100E308432EAA34F055BC29E7E3E6D1B4A90800308E017BCA87C1B70D0398B1828612BCB175988762BA1D8FA2E3541875CE426979F5C9120E8502C7161C17215A8C010899044A7B7C2016C6C98A8A277E40E104043752CB322547886FF252C110343DC60068628FD00CC21748F2A981C12DE3021FEB1C98A90E51F6FE8BD7386E693A1E1DE26BF071756E11C39247988770A7BD60907B06DBC00736DD05473E401FF8000D72776CAC00B2AB00376D03CE7805017310DFDE000E5C06AFCA50CAD3702FB2469E5D0060A360392B04F8DA038142137B8B71036F17F27A42E80E21052A10E503056BD500C62177089906F81C4042F4181D3247ABC100EB9B0811DC811EEF00CC9610E23B005BF6008C5600776000B1A96590DC062749608EEF00F1C2081832710E900078A80550F600387400A19600393F00438405DF9B268CCC141062215E9C008543009A4A0013D300D87A0018710094D80042E20150BFF704404C07C03C0039EB16C527536D3D52
